### ISSUE TITLE
"posterize -b" produces larger files size at worse qualities 

### ISSUE THREAD

**Issue by skaraman** [kornelski/mediancut-posterizer#13]
I've tried a number of different options and no matter what I try, I can't get the command line of posterize -b to produce the same quality and file size as ImageAlpha.app.

Basically I'm taking ~300KB png and in ImageAlpha using Blurizer and about 64 quality is what I want and it gives me ~150KB png that looks great, but this process is manual.

Using the CLI I take the same png and provide these options "posterize -b 64" and the image looks really bad, broken, artifacts and the file size is ~300KB. I use "posterize -b -Q80" and the image looks good but the file size is 450KB+. 

I tried lowest quality settings just to see and with 2 levels i get ~260KB image with total distortion of the image. At -Q10 I get a slightly artifacted image still relatively ok looking but ~400KB

Any help?

**Comment by skaraman** [comment]
![test blur](https://user-images.githubusercontent.com/2840020/40333134-bc68676c-5d0b-11e8-9380-74230d1d9dce.png)
![test](https://user-images.githubusercontent.com/2840020/40333135-bc7e045a-5d0b-11e8-8771-5d4541d3b55f.png)
![test post](https://user-images.githubusercontent.com/2840020/40333136-bc9a17da-5d0b-11e8-9b39-f9b0785fc6ee.png)

Here's an example test blur is using ImageAlpha, test post is using posterize -b 128 [in] [out]

**Comment by kornelski** [comment]
ImageAlpha shows a different scale in the UI (I couldn't be bothered to change scale of the slider for each tool :), so the numbers from the UI won't make any sense at all for the command line tool.

**Comment by skaraman** [comment]
Ok I can understand that but even if I use like 220-250 levels to get around the quality I want, the resulting file size is much larger than the raw/source.

**Comment by skaraman** [comment]
210 levels 638KB - ![test 210](https://user-images.githubusercontent.com/2840020/40387855-bcfc7e4a-5dc2-11e8-8ab9-2d44e6498515.png)
235 levels 639KB - ![test 235](https://user-images.githubusercontent.com/2840020/40387856-bd1ef650-5dc2-11e8-9564-7143a9255b2e.png)
250 levels 650KB - ![test 250](https://user-images.githubusercontent.com/2840020/40387857-bd39bfb2-5dc2-11e8-84a1-7ff0f177bca1.png)
255 levels 552 KB ![test 255](https://user-images.githubusercontent.com/2840020/40387858-bd513b88-5dc2-11e8-945d-ff0389a589e5.png)

**Comment by kornelski** [comment]
Your file doesn't have the right PNG filters applied. If I run it through lossless ImageOptim it decreases from 600KB down to 80KB.

I can't reproduce the problem with the binary I shipped with ImageAlpha. 

Perhaps you have a buggy version of libpng?

**Comment by skaraman** [comment]
thanks for your help it's definitely an issue in my libpng install
